sudo: false

language:
    - php
    - node_js

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

node_js:
    - stable

env:
    - WP_VERSION=trunk WP_MULTISITE=1
    - WP_VERSION=latest WP_MULTISITE=1

branches:
    only:
        - master

before_script:
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - source $DEV_LIB_PATH/travis.before_script.sh
    - export LIMIT_TRAVIS_PR_CHECK_SCOPE=patches

script:
    - $DEV_LIB_PATH/travis.script.sh

after_script:
    - $DEV_LIB_PATH/travis.after_script.sh
